name: report-tests
on: [push]
jobs:
  tests-with-reporting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.13'
      - run: npm install
      - run: npx jest --json --outputFile=result.json --testLocationInResults
      - uses: tanmen/jest-reporter@v1
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
